import { useMemo, useState } from "react";
import type { FunnelDefinition } from "../schema/v1";
import { deleteRemoteAssetObject, fetchAssetInventory } from "./remoteAssetClient";
import { classifyInventory, removePreviousVersion, storageSummary, type ClassifiedObject } from "./remoteAssetCleanup";

type Props = { funnel: FunnelDefinition; token: string; onChange: (funnel: FunnelDefinition) => void };
const mib = (size: number) => `${Math.round(size / 1024 / 1024 * 10) / 10} MiB`;

export function AssetCleanupPanel({ funnel, token, onChange }: Props) {
  const [items, setItems] = useState<ClassifiedObject[]>(); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [results, setResults] = useState<Record<string, string>>({});
  const summary = useMemo(() => items ? storageSummary(items) : undefined, [items]);
  const refresh = async () => { if (!token) return setError("Gerenciamento remoto desativado."); setLoading(true); setError(""); try { const response = await fetchAssetInventory(funnel.id, token); setItems(classifyInventory(funnel, response.objects)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar os arquivos."); } finally { setLoading(false); } };
  const deletable = (item: ClassifiedObject) => item.classification !== "current";
  const cleanup = async () => { if (!selected.length || !confirm("Os arquivos selecionados serão removidos permanentemente do armazenamento.")) return; const fresh = items ? classifyInventory(funnel, items) : []; let next = funnel; const nextItems = [...fresh]; const nextResults: Record<string, string> = {}; for (const key of selected) { const item = fresh.find((x) => x.key === key); const inferredAssetId = key.split("/")[3]; if (!item || !deletable(item) || !inferredAssetId) { nextResults[key] = "BLOQUEADO"; continue; } try { await deleteRemoteAssetObject(next.id, item.assetId || inferredAssetId, key, token); nextResults[key] = "EXCLUÍDO"; if (item.classification === "old_version" && item.assetId) next = removePreviousVersion(next, item.assetId, key); const index = nextItems.findIndex((x) => x.key === key); if (index >= 0) nextItems.splice(index, 1); } catch { nextResults[key] = "FALHOU"; } } onChange(next); setItems(nextItems); setResults(nextResults); setSelected([]); };
  return <section className="mt-4 grid gap-2 border-t border-zinc-700 pt-3"><b>ARMAZENAMENTO</b>{!token ? <small>Gerenciamento remoto desativado. Configure a autorização para revisar a limpeza.</small> : <button onClick={() => void refresh()}>{loading ? "CARREGANDO..." : "ATUALIZAR INVENTÁRIO"}</button>}{summary ? <small>Atual: {mib(summary.current)} · Versões anteriores: {mib(summary.old)} · Possíveis órfãos: {mib(summary.orphan)} · Potencial de limpeza: {mib(summary.old + summary.orphan)}</small> : <small>Atualize o inventário para calcular.</small>}{items && <details><summary>REVISAR LIMPEZA</summary><div className="grid gap-1">{items.filter(deletable).map((item) => <label key={item.key}><input type="checkbox" checked={selected.includes(item.key)} onChange={() => setSelected((keys) => keys.includes(item.key) ? keys.filter((key) => key !== item.key) : [...keys, item.key])} /> {item.classification === "old_version" ? "VERSÃO ANTERIOR" : "POSSÍVEL ARQUIVO ÓRFÃO"} · {item.key.split("/").at(-1)} · {mib(item.size)} {results[item.key] && `— ${results[item.key]}`}</label>)}<small>{selected.length} arquivos selecionados</small><button disabled title="Exclusão remota temporariamente desativada enquanto esta função é validada.">EXCLUIR SELECIONADOS</button><small>Exclusão remota temporariamente desativada enquanto esta função é validada.</small></div></details>}{error && <small className="text-red-400">{error}</small>}</section>;
}
