import { useEffect, useMemo, useRef, useState } from "react";
import type { AssetRef, FunnelDefinition } from "../schema/v1";
import { isStudioMediaType, studioMediaTypeForMime, uploadPermanentAsset, type UploadStatus } from "./permanentUpload";
import { findAssetUsages, uid } from "./studioState";
import { addPermanentUrl, assetStatus, assetSummary, filterAssets, promoteAssetInFunnel, removeUnusedAsset, renameAsset, replacePermanentAsset, type AssetFilter } from "./assetManagerState";
import { AssetCleanupPanel } from "./AssetCleanupPanel";
import { AssetVersionInspector } from "./AssetVersionInspector";

export const ASSET_UPLOAD_SESSION_KEY = "funnel-studio:upload-token";
const ACCEPT = "video/mp4,video/webm,audio/mpeg,audio/mp4,audio/wav,audio/ogg,image/jpeg,image/png,image/webp";
type QueueMode = "promote" | "direct" | "replace";
type QueueItem = { id: string; assetId: string; file: File; mode: QueueMode; status: UploadStatus; progress: number; error?: string };
type PickMode = "local" | "direct" | "replace" | "reattach-promote";
type Props = { funnel: FunnelDefinition; urls: Record<string, string>; onChange: (next: FunnelDefinition) => void; onAttachPreview: (file: File, assetId?: string) => void; onRevoke: (assetId: string) => void; onClose: () => void; onOpenUsage: (path: string) => void };
const fileName = (asset: AssetRef) => asset.source === "preview" ? asset.fileName : asset.fileName || asset.url.split("/").at(-1) || "Arquivo";
const statusLabel = (asset: AssetRef, urls: Record<string, string>) => asset.source === "permanent" ? "PERMANENTE" : assetStatus(asset, urls) === "unresolved" ? "PRECISA SER REANEXADO" : "LOCAL — SOMENTE PREVIEW";
const typeLabel = (type: AssetRef["mediaType"]) => type === "video" ? "Vídeo" : type === "audio" ? "Áudio" : "Imagem";
const humanUploadError = (message: string) => message.includes("maior") ? "O limite atual é 90 MiB por arquivo." : message.includes("autoriz") ? "A autorização de upload não é válida." : message.includes("conex") ? "Sem conexão com o servidor." : message;

export function AssetManager({ funnel, urls, onChange, onAttachPreview, onRevoke, onClose, onOpenUsage }: Props) {
  const [filter, setFilter] = useState<AssetFilter>("all"); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState<string>(); const [token, setToken] = useState(""); const [tokenDraft, setTokenDraft] = useState(""); const [showToken, setShowToken] = useState(false); const [queue, setQueue] = useState<QueueItem[]>([]); const [permanentUrl, setPermanentUrl] = useState(""); const [permanentName, setPermanentName] = useState(""); const [permanentType, setPermanentType] = useState<AssetRef["mediaType"]>("video");
  const input = useRef<HTMLInputElement>(null); const controllers = useRef(new Map<string, AbortController>()); const files = useRef(new Map<string, File>());
  useEffect(() => { setToken(sessionStorage.getItem(ASSET_UPLOAD_SESSION_KEY) || ""); }, []);
  const assets = useMemo(() => filterAssets(funnel.assets, urls, filter, query), [filter, funnel.assets, query, urls]);
  const selected = funnel.assets.find((asset) => asset.id === selectedId) || assets[0]; const summary = assetSummary(funnel, urls);
  const patchQueue = (id: string, patch: Partial<QueueItem>) => setQueue((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const valid = (file: File) => isStudioMediaType(file.type) && !!studioMediaTypeForMime(file.type);
  const attachLocal = (file: File, assetId?: string) => { if (!valid(file)) return alert("Este tipo de arquivo não é aceito."); const id = assetId || uid(studioMediaTypeForMime(file.type)!); files.current.set(id, file); onAttachPreview(file, id); setSelectedId(id); };
  const pick = (mode: PickMode, assetId?: string) => { if (!input.current) return; input.current.dataset["mode"] = mode; input.current.dataset["assetId"] = assetId || ""; input.current.click(); };
  const saveToken = () => { if (!tokenDraft.trim()) return; sessionStorage.setItem(ASSET_UPLOAD_SESSION_KEY, tokenDraft.trim()); setToken(tokenDraft.trim()); setTokenDraft(""); setShowToken(false); };
  const clearToken = () => { sessionStorage.removeItem(ASSET_UPLOAD_SESSION_KEY); setToken(""); };
  const execute = async (item: QueueItem) => { const controller = new AbortController(); controllers.current.set(item.id, controller); try { const result = await uploadPermanentAsset({ funnelId: funnel.id, assetId: item.assetId, file: item.file, token, signal: controller.signal, onProgress: (progress, status) => patchQueue(item.id, { progress, status }) }); const next = item.mode === "promote" ? promoteAssetInFunnel(funnel, item.assetId, result) : item.mode === "replace" ? replacePermanentAsset(funnel, item.assetId, result) : { ...funnel, assets: [...funnel.assets, { id: item.assetId, mediaType: studioMediaTypeForMime(item.file.type)!, source: "permanent" as const, url: result.src, fileName: result.filename, contentType: result.contentType, size: result.size, uploadedAt: result.uploadedAt, r2Key: result.key, etag: result.etag }] }; onChange(next); if (item.mode === "promote") onRevoke(item.assetId); patchQueue(item.id, { status: "completed", progress: 100 }); setSelectedId(item.assetId); } catch (error) { const cancelled = error instanceof Error && error.name === "PermanentUploadError" && (error as { code?: string }).code === "cancelled"; patchQueue(item.id, { status: cancelled ? "cancelled" : "error", error: humanUploadError(error instanceof Error ? error.message : "Não foi possível salvar este arquivo.") }); } finally { controllers.current.delete(item.id); } };
  const enqueue = (assetId: string, file: File, mode: QueueMode) => { if (!token) { setShowToken(true); return; } const item: QueueItem = { id: uid("upload"), assetId, file, mode, status: "waiting", progress: 0 }; setQueue((items) => [...items, item]); void execute(item); };
  const handleFile = (file: File, mode: PickMode, assetId?: string) => { if (mode === "local") return attachLocal(file, assetId); if (mode === "direct") { if (!valid(file)) return alert("Este tipo de arquivo não é aceito."); return enqueue(uid(studioMediaTypeForMime(file.type)!), file, "direct"); } const asset = funnel.assets.find((item) => item.id === assetId); if (!asset) return; if (mode === "replace") return enqueue(asset.id, file, "replace"); attachLocal(file, asset.id); enqueue(asset.id, file, "promote"); };
  const preview = selected?.source === "permanent" ? selected.url : selected ? urls[selected.id] : undefined; const usage = selected ? findAssetUsages(funnel, selected.id) : [];
  return <div className="fixed inset-0 z-[100] bg-black/70 p-4 text-zinc-100"><section className="mx-auto grid h-full max-w-6xl grid-rows-[auto_auto_1fr_auto] gap-3 rounded-xl border border-zinc-700 bg-zinc-950 p-4">
    <header className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-bold">BIBLIOTECA DE MÍDIA</h2><small>{summary.total} arquivos · {summary.permanent} permanentes · {summary.local} locais · {summary.unresolved} precisam ser reanexados · {queue.filter((item) => item.status === "error").length} com erro</small></div><button onClick={onClose}>FECHAR</button></header>
    <div className="flex flex-wrap gap-2"><input placeholder="BUSCAR ARQUIVO" value={query} onChange={(event) => setQuery(event.target.value)} />{(["all", "video", "audio", "image", "local", "permanent", "problem"] as AssetFilter[]).map((item) => <button key={item} className={filter === item ? "bg-blue-600" : ""} onClick={() => setFilter(item)}>{item === "all" ? "TODOS" : item === "video" ? "VÍDEOS" : item === "audio" ? "ÁUDIOS" : item === "image" ? "IMAGENS" : item === "local" ? "LOCAIS" : item === "permanent" ? "PERMANENTES" : "COM PROBLEMA"}</button>)}<button onClick={() => pick("local")}>+ ADICIONAR ARQUIVO</button><button disabled={!token} onClick={() => pick("direct")}>ENVIAR DIRETO</button>{token ? <><b className="text-emerald-400">UPLOAD PERMANENTE ATIVADO</b><button onClick={clearToken}>REMOVER AUTORIZAÇÃO</button></> : <button onClick={() => setShowToken(true)}>CONFIGURAR UPLOAD</button>}</div>
    {showToken && <div className="flex gap-2"><input type="password" autoComplete="off" placeholder="TOKEN DE AUTORIA" value={tokenDraft} onChange={(event) => setTokenDraft(event.target.value)} /><button onClick={saveToken}>ATIVAR UPLOAD</button></div>}
    <input ref={input} className="hidden" type="file" accept={ACCEPT} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) handleFile(file, (event.currentTarget.dataset["mode"] || "local") as PickMode, event.currentTarget.dataset["assetId"] || undefined); event.currentTarget.value = ""; }} />
    <div className="grid min-h-0 grid-cols-[1fr_340px] gap-4"><div className="overflow-auto rounded border border-dashed border-zinc-700 p-3" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); Array.from(event.dataTransfer.files).forEach((file) => attachLocal(file)); }}><p className="mb-2 text-xs text-zinc-400">Arraste arquivos aqui ou use “Adicionar arquivo”.</p><div className="grid grid-cols-2 gap-2 md:grid-cols-3">{assets.map((asset) => <button key={asset.id} onClick={() => setSelectedId(asset.id)} className="grid gap-1 rounded border border-zinc-700 p-2 text-left"><div className="grid h-24 place-items-center bg-zinc-900 text-zinc-500">{typeLabel(asset.mediaType)}</div><b className="truncate">{fileName(asset)}</b><small>{statusLabel(asset, urls)}</small><small>{asset.source === "permanent" && asset.size ? `${Math.round(asset.size / 1024 / 1024 * 10) / 10} MiB` : "tamanho desconhecido"}</small><small>USADO EM {findAssetUsages(funnel, asset.id).length} LUGARES</small></button>)}</div></div>
      <aside className="overflow-auto rounded border border-zinc-700 p-3">{selected ? <div className="grid gap-2"><b>{fileName(selected)}</b><small>{typeLabel(selected.mediaType)} · {statusLabel(selected, urls)}</small>{selected.source === "permanent" && <AssetVersionInspector funnel={funnel} asset={selected} token={token} onChange={onChange} />}{preview && selected.mediaType === "video" && <video controls src={preview} />}{preview && selected.mediaType === "audio" && <audio controls src={preview} />}{preview && selected.mediaType === "image" && <img src={preview} alt={fileName(selected)} />}{selected.source === "preview" && !urls[selected.id] && <button onClick={() => pick(token ? "reattach-promote" : "local", selected.id)}>{token ? "REANEXAR E TORNAR PERMANENTE" : "REANEXAR"}</button>}{selected.source === "preview" && urls[selected.id] && <button onClick={() => { const file = files.current.get(selected.id); if (file) enqueue(selected.id, file, "promote"); else pick("local", selected.id); }}>TORNAR PERMANENTE</button>}{selected.source === "permanent" && <button onClick={() => pick("replace", selected.id)}>SUBSTITUIR ARQUIVO</button>}<label>Nome<input value={fileName(selected)} onChange={(event) => onChange(renameAsset(funnel, selected.id, event.target.value))} /></label><b>USADO EM {usage.length} LUGARES</b>{usage.map((item) => <button className="text-left text-blue-400" key={item.path} onClick={() => onOpenUsage(item.path)}>ABRIR — {item.label}</button>)}{usage.length ? <small>Este arquivo está sendo usado. Remova as referências antes de removê-lo do projeto.</small> : <button onClick={() => { onRevoke(selected.id); onChange(removeUnusedAsset(funnel, selected.id)); setSelectedId(undefined); }}>REMOVER DO PROJETO</button>}<details><summary>DETALHES TÉCNICOS</summary><pre className="whitespace-pre-wrap text-xs">{JSON.stringify(selected, null, 2)}</pre></details></div> : <p>Selecione um arquivo.</p>}<div className="mt-4 grid gap-2 border-t border-zinc-700 pt-3"><b>COLAR URL PERMANENTE</b><input placeholder="https://... ou /media/..." value={permanentUrl} onChange={(event) => setPermanentUrl(event.target.value)} /><input placeholder="Nome opcional" value={permanentName} onChange={(event) => setPermanentName(event.target.value)} /><select value={permanentType} onChange={(event) => setPermanentType(event.target.value as AssetRef["mediaType"])}><option value="video">Vídeo</option><option value="audio">Áudio</option><option value="image">Imagem</option></select><button onClick={() => { if (!permanentUrl.trim()) return; onChange(addPermanentUrl(funnel, permanentUrl.trim(), permanentType, permanentName.trim() || undefined)); setPermanentUrl(""); setPermanentName(""); }}>ADICIONAR URL</button></div></aside></div>
    <AssetCleanupPanel funnel={funnel} token={token} onChange={onChange} />
    <section className="max-h-40 overflow-auto border-t border-zinc-800 pt-2">{queue.map((item) => <div className="flex items-center gap-2" key={item.id}><span className="w-40 truncate">{item.file.name}</span><progress value={item.progress} max="100" /><span>{item.status.toUpperCase()} {item.progress}%</span>{item.status === "uploading" && <button onClick={() => controllers.current.get(item.id)?.abort()}>CANCELAR</button>}{item.status === "error" && <button onClick={() => void execute(item)}>TENTAR NOVAMENTE</button>}<small className="text-red-400">{item.error}</small></div>)}</section>
  </section></div>;
}
