import { useState } from "react";
import type { ActionDefinition, FunnelDefinition, SceneEventDefinition, SceneDefinition, TriggerDefinition } from "../schema/v1";
import { actionFromGuided, createGuidedInteraction, deleteGuidedInteraction, duplicateGuidedInteraction, guidedInteractionReferences, triggerFromGuided, updateGuidedInteraction } from "./guidedState";
import { GuidedPreview, formatTime } from "./GuidedPreview";
import { uid } from "./studioState";
import { InlineMediaPicker } from "./InlineMediaPicker";

type Essential = Extract<SceneEventDefinition["block"], "quiz" | "notification" | "audio" | "scene_transition">;
const labels: Record<Essential, string> = { quiz: "Pergunta", notification: "Notificação", audio: "Áudio", scene_transition: "Ir para outra cena" };
const triggerLabel = (trigger: TriggerDefinition) => trigger.kind === "SCENE_START" ? "no começo do vídeo" : trigger.kind === "TIME" ? `em ${formatTime(trigger.seconds)}` : trigger.kind === "BEFORE_END" ? `${trigger.seconds.toFixed(2)}s antes do final` : trigger.kind === "VIDEO_END" ? "quando o vídeo terminar" : "depois de outra interação";
const actionLabel = (action?: ActionDefinition) => !action ? "continua o vídeo" : action.type === "RESUME_VIDEO" ? "continua o vídeo" : action.type === "NEXT_SCENE" ? "vai para a próxima cena" : action.type === "GO_TO_SCENE" ? "vai para outra cena" : action.type === "OPEN_EVENT" ? "abre outra interação" : "encerra";

export function GuidedEssentialInteractions({ funnel, scene, urls, onChange, onAttachAsset, onAttachPreviewFile }: { funnel: FunnelDefinition; scene: SceneDefinition; urls: Record<string, string>; onChange: (funnel: FunnelDefinition) => void; onAttachAsset: () => void; onAttachPreviewFile: ((file: File, assetId?: string) => void) | undefined }) {
  const [editing, setEditing] = useState<string | null>(null);
  const [pickingTime, setPickingTime] = useState<string | null>(null);
  const events = scene.events.filter((event): event is Extract<SceneEventDefinition, { block: Essential }> => ["quiz", "notification", "audio", "scene_transition"].includes(event.block));
  const create = (block: Essential) => {
    const next = createGuidedInteraction(funnel, scene.id, block);
    onChange(next);
    setEditing(next.scenes.find((item) => item.id === scene.id)?.events.at(-1)?.id || null);
  };
  const update = (event: SceneEventDefinition) => onChange(updateGuidedInteraction(funnel, scene.id, event));
  const addUrl = (type: "audio" | "image") => {
    const url = prompt(`URL permanente do ${type === "audio" ? "áudio" : "avatar"}`);
    if (!url) return;
    const id = uid(type);
    onChange({ ...funnel, assets: [...funnel.assets, { id, mediaType: type, source: "permanent", url }] });
  };
  return <section className="grid gap-4">
    <div><h2>INTERATIVIDADE</h2><p>Escolha algo que pode acontecer durante esta cena.</p></div>
    <div className="flex flex-wrap gap-2">
      {(Object.keys(labels) as Essential[]).map((block) => <button key={block} onClick={() => create(block)}>+ {labels[block]}</button>)}
    </div>
    {events.map((event) => <div className="border border-zinc-700 rounded p-3 grid gap-2" key={event.id}>
      <div className="flex justify-between gap-2"><b>{summaryTitle(event)}</b><span className="text-zinc-400">{triggerLabel(event.trigger)}</span></div>
      <small>{summaryAfter(event, funnel)}</small>
      <div className="flex flex-wrap gap-2">
        <button onClick={() => setEditing(editing === event.id ? null : event.id)}>EDITAR</button>
        <button onClick={() => setEditing(event.id)}>TESTAR</button>
        <button onClick={() => onChange(duplicateGuidedInteraction(funnel, scene.id, event.id))}>DUPLICAR</button>
        <button onClick={() => { const refs = guidedInteractionReferences(funnel, event.id); if (refs.length && !confirm(`Esta interação é usada em ${refs.length} lugares:\n${refs.join("\n")}\n\nExcluir mesmo assim?`)) return; onChange(deleteGuidedInteraction(funnel, scene.id, event.id)); }}>EXCLUIR</button>
      </div>
      {editing === event.id && <Editor event={event} funnel={funnel} scene={scene} urls={urls} update={update} onClose={() => setEditing(null)} onAddUrl={addUrl} onAttachAsset={onAttachAsset} onFunnelChange={onChange} onAttachPreviewFile={onAttachPreviewFile} pickingTime={pickingTime === event.id} setPickingTime={(open) => setPickingTime(open ? event.id : null)} />}
    </div>)}
    {events.length > 0 && <div className="rounded bg-zinc-900 p-3"><b>RESUMO DA CENA</b>{events.map((event) => <p key={event.id}>• {summaryTitle(event)} — {triggerLabel(event.trigger)}. {summaryAfter(event, funnel)}</p>)}</div>}
  </section>;
}

function Editor({ event, funnel, scene, urls, update, onClose, onAddUrl, onAttachAsset, onFunnelChange, onAttachPreviewFile, pickingTime, setPickingTime }: { event: Extract<SceneEventDefinition, { block: Essential }>; funnel: FunnelDefinition; scene: SceneDefinition; urls: Record<string, string>; update: (event: SceneEventDefinition) => void; onClose: () => void; onAddUrl: (type: "audio" | "image") => void; onAttachAsset: () => void; onFunnelChange: (funnel: FunnelDefinition) => void; onAttachPreviewFile: ((file: File, assetId?: string) => void) | undefined; pickingTime: boolean; setPickingTime: (open: boolean) => void }) {
  const setTrigger = (trigger: TriggerDefinition) => update({ ...event, trigger });
  return <div className="mt-2 rounded bg-zinc-950 p-3 grid gap-3">
    <b>1. Quando isso acontece?</b>
    <select value={event.trigger.kind} onChange={(e) => { const kind = e.target.value; setTrigger(kind === "SCENE_START" ? triggerFromGuided("start") : kind === "TIME" ? triggerFromGuided("time", 0) : kind === "BEFORE_END" ? triggerFromGuided("before_end", 2) : kind === "VIDEO_END" ? triggerFromGuided("end") : triggerFromGuided("after", 0, scene.events.find((item) => item.id !== event.id)?.id || "")); }}>
      <option value="SCENE_START">NO COMEÇO DO VÍDEO</option><option value="TIME">EM UM MOMENTO ESPECÍFICO</option><option value="BEFORE_END">POUCO ANTES DO FINAL</option><option value="VIDEO_END">QUANDO O VÍDEO TERMINAR</option><option value="INTERACTION_COMPLETE">DEPOIS DE OUTRA INTERAÇÃO</option>
    </select>
    {event.trigger.kind === "TIME" && <><input aria-label="momento" type="number" step="0.01" value={event.trigger.seconds} onChange={(e) => setTrigger(triggerFromGuided("time", Number(e.target.value)))} /><button onClick={() => setPickingTime(!pickingTime)}>ESCOLHER MOMENTO DO VÍDEO</button>{pickingTime && <GuidedPreview funnel={funnel} scene={scene} urls={urls} onMoment={(seconds) => { setTrigger(triggerFromGuided("time", seconds)); setPickingTime(false); }} />}</>}
    {event.trigger.kind === "BEFORE_END" && <label>Quantos segundos antes? <input type="number" step="0.01" value={event.trigger.seconds} onChange={(e) => setTrigger(triggerFromGuided("before_end", Number(e.target.value)))} /></label>}
    {event.trigger.kind === "INTERACTION_COMPLETE" && <select value={event.trigger.interactionId} onChange={(e) => setTrigger(triggerFromGuided("after", 0, e.target.value))}><option value="">Escolha uma interação</option>{scene.events.filter((item) => item.id !== event.id).map((item) => <option key={item.id} value={item.id}>{summaryTitle(item)}</option>)}</select>}
    {event.block === "quiz" && <QuizEditor event={event} update={update} />}
    {event.block === "notification" && <NotificationEditor event={event} funnel={funnel} update={update} onAddUrl={onAddUrl} onAttachAsset={onAttachAsset} />}
    {event.block === "audio" && <AudioEditor event={event} funnel={funnel} urls={urls} update={update} onAddUrl={onAddUrl} onAttachAsset={onAttachAsset} />}
    {onAttachPreviewFile && event.block === "notification" && <><InlineMediaPicker label="Avatar" mediaType="image" funnel={funnel} urls={urls} value={event.avatarAssetId} onSelect={(assetId) => update({ ...event, avatarAssetId: assetId })} onChange={onFunnelChange} onAttachPreview={onAttachPreviewFile} /><InlineMediaPicker label="Som da notificação" mediaType="audio" funnel={funnel} urls={urls} value={event.soundAssetId} onSelect={(assetId) => update({ ...event, soundAssetId: assetId })} onChange={onFunnelChange} onAttachPreview={onAttachPreviewFile} /></>}
    {onAttachPreviewFile && event.block === "audio" && <InlineMediaPicker label="Áudio" mediaType="audio" funnel={funnel} urls={urls} value={event.assetId} onSelect={(assetId) => update({ ...event, assetId: assetId || "" })} onChange={onFunnelChange} onAttachPreview={onAttachPreviewFile} />}
    {event.block === "scene_transition" && <label>Para qual cena? <select value={event.targetSceneId} onChange={(e) => update({ ...event, targetSceneId: e.target.value, actions: [{ type: "GO_TO_SCENE", sceneId: e.target.value }] })}><option value="">Escolha uma cena</option>{funnel.scenes.filter((item) => item.id !== scene.id).map((item, index) => <option key={item.id} value={item.id}>Cena {index + 1} — {item.title}</option>)}</select>{!event.targetSceneId && <small>Escolha para qual cena continuar.</small>}</label>}
    {event.block !== "notification" && event.block !== "scene_transition" && <Actions value={event.actions[0]} funnel={funnel} scene={scene} onChange={(action) => update({ ...event, actions: [action] } as SceneEventDefinition)} />}
    {event.block === "notification" && <><Actions label="Quando a pessoa tocar" value={event.onTap[0]} funnel={funnel} scene={scene} onChange={(action) => update({ ...event, onTap: [action] })} /><Actions label="E se ela fechar" value={event.onDismiss[0]} funnel={funnel} scene={scene} onChange={(action) => update({ ...event, onDismiss: [action] })} /></>}
    <div><b>5. Testar agora</b><GuidedPreview funnel={funnel} scene={scene} urls={urls} testEventId={event.id} /></div>
    <button onClick={onClose}>SALVAR</button>
  </div>;
}

function QuizEditor({ event, update }: { event: Extract<SceneEventDefinition, { block: "quiz" }>; update: (event: SceneEventDefinition) => void }) { const question = event.questions[0]!; const options = question.options; const setOptions = (next: typeof options) => update({ ...event, questions: [{ ...question, options: next }] }); return <><b>2. Sua pergunta</b><input value={question.title} onChange={(e) => update({ ...event, title: e.target.value || "Pergunta", questions: [{ ...question, title: e.target.value }] })} placeholder="Pergunta" />{options.map((option, index) => <div className="flex gap-2" key={option.id}><input value={option.label} onChange={(e) => setOptions(options.map((item) => item.id === option.id ? { ...item, label: e.target.value } : item))} /><button onClick={() => setOptions([...options, { ...option, id: uid("option") }])}>DUPLICAR</button><button disabled={options.length <= 2} onClick={() => setOptions(options.filter((item) => item.id !== option.id))}>EXCLUIR</button><button disabled={index === 0} onClick={() => setOptions(options.map((item, i, all) => i === index ? all[index - 1]! : i === index - 1 ? option : item))}>↑</button></div>)}<button onClick={() => setOptions([...options, { id: uid("option"), label: "Nova opção" }])}>+ ADICIONAR OPÇÃO</button>{options.length < 2 && <small>Adicione pelo menos duas opções.</small>}<details><summary>CONFIGURAÇÕES AVANÇADAS</summary><select value={event.variant || "default"} onChange={(e) => update({ ...event, variant: e.target.value as any })}><option value="default">Padrão</option><option value="cinematic">Cinemático</option><option value="immersive">Imersivo</option></select><label><input type="checkbox" checked={event.showProgress || false} onChange={(e) => update({ ...event, showProgress: e.target.checked })} /> Mostrar progresso</label></details></>; }
function NotificationEditor({ event, funnel, update, onAddUrl, onAttachAsset }: { event: Extract<SceneEventDefinition, { block: "notification" }>; funnel: FunnelDefinition; update: (event: SceneEventDefinition) => void; onAddUrl: (type: "audio" | "image") => void; onAttachAsset: () => void }) { const images = funnel.assets.filter((asset) => asset.mediaType === "image"); const audio = funnel.assets.filter((asset) => asset.mediaType === "audio"); return <><b>2. Notificação</b><input value={event.appName} onChange={(e) => update({ ...event, appName: e.target.value })} placeholder="Aplicativo" /><input value={event.senderName} onChange={(e) => update({ ...event, senderName: e.target.value })} placeholder="Quem enviou?" /><textarea value={event.message} onChange={(e) => update({ ...event, message: e.target.value })} placeholder="Mensagem" />{!event.message && <small>Escreva a mensagem da notificação.</small>}<AssetSelect label="Foto / avatar" value={event.avatarAssetId} assets={images} onChange={(id) => update({ ...event, avatarAssetId: id || undefined })} onAdd={() => onAddUrl("image")} onAttach={onAttachAsset} /><AssetSelect label="Som" value={event.soundAssetId} assets={audio} onChange={(id) => update({ ...event, soundAssetId: id || undefined })} onAdd={() => onAddUrl("audio")} onAttach={onAttachAsset} /><label><input type="checkbox" checked={event.autoDismiss || false} onChange={(e) => update({ ...event, autoDismiss: e.target.checked })} /> Fechar automaticamente</label></>; }
function AudioEditor({ event, funnel, urls, update, onAddUrl, onAttachAsset }: { event: Extract<SceneEventDefinition, { block: "audio" }>; funnel: FunnelDefinition; urls: Record<string, string>; update: (event: SceneEventDefinition) => void; onAddUrl: (type: "audio" | "image") => void; onAttachAsset: () => void }) { const audio = funnel.assets.filter((asset) => asset.mediaType === "audio"); const src = funnel.assets.find((asset) => asset.id === event.assetId); const url = src?.source === "permanent" ? src.url : src?.source === "preview" ? urls[src.id] : undefined; return <><b>2. Áudio</b><AssetSelect label="Áudio" value={event.assetId} assets={audio} onChange={(id) => update({ ...event, assetId: id })} onAdd={() => onAddUrl("audio")} onAttach={onAttachAsset} />{!event.assetId && <small>Escolha um áudio.</small>}<label>Volume <input type="range" min="0" max="1" step="0.01" value={event.volume ?? 1} onChange={(e) => update({ ...event, volume: Number(e.target.value) })} /></label><label><input type="checkbox" checked={event.loop || false} onChange={(e) => update({ ...event, loop: e.target.checked })} /> Repetir</label><button onClick={() => { if (!url) return alert("Escolha um áudio válido."); const player = new Audio(url); player.onerror = () => alert("Não foi possível reproduzir este áudio."); void player.play().catch(() => alert("Não foi possível reproduzir este áudio.")); }}>▶ TESTAR ÁUDIO</button></>; }
function AssetSelect({ label, value, assets, onChange, onAdd, onAttach }: { label: string; value?: string | undefined; assets: FunnelDefinition["assets"]; onChange: (id: string) => void; onAdd: () => void; onAttach: () => void }) { return <div><label>{label} <select value={value || ""} onChange={(e) => onChange(e.target.value)}><option value="">Selecionar arquivo do projeto</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.id}{asset.source === "preview" ? " (local)" : ""}</option>)}</select></label><button onClick={onAdd}>+ URL PERMANENTE</button><button onClick={onAttach}>+ ARQUIVO LOCAL PARA PREVIEW</button></div>; }
function Actions({ label = "3. Depois disso", value, funnel, scene, onChange }: { label?: string; value?: ActionDefinition | undefined; funnel: FunnelDefinition; scene: SceneDefinition; onChange: (action: ActionDefinition) => void }) { const kind = value?.type || "RESUME_VIDEO"; return <div className="grid gap-1"><b>{label}</b><select value={kind} onChange={(e) => { const type = e.target.value; onChange(type === "RESUME_VIDEO" ? { type } : type === "NEXT_SCENE" ? { type } : type === "STOP" ? { type } : type === "GO_TO_SCENE" ? { type, sceneId: funnel.scenes.find((item) => item.id !== scene.id)?.id || "" } : { type: "OPEN_EVENT", eventId: scene.events.find((item) => item.id)?.id || "" }); }}><option value="RESUME_VIDEO">CONTINUAR O VÍDEO</option><option value="NEXT_SCENE">IR PARA A PRÓXIMA CENA</option><option value="GO_TO_SCENE">IR PARA OUTRA CENA</option><option value="OPEN_EVENT">ABRIR OUTRA INTERAÇÃO</option><option value="STOP">ENCERRAR</option></select>{kind === "GO_TO_SCENE" && <select value={value?.type === "GO_TO_SCENE" ? value.sceneId : ""} onChange={(e) => onChange({ type: "GO_TO_SCENE", sceneId: e.target.value })}><option value="">Escolha uma cena</option>{funnel.scenes.filter((item) => item.id !== scene.id).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>}{kind === "OPEN_EVENT" && <select value={value?.type === "OPEN_EVENT" ? value.eventId : ""} onChange={(e) => onChange({ type: "OPEN_EVENT", eventId: e.target.value })}><option value="">Escolha uma interação</option>{scene.events.map((item) => <option key={item.id} value={item.id}>{summaryTitle(item)}</option>)}</select>}</div>; }
function summaryTitle(event: SceneEventDefinition) { return event.block === "quiz" ? `❓ ${event.questions[0]?.title || event.title}` : event.block === "notification" ? `🔔 ${event.senderName}` : event.block === "audio" ? "🔊 Áudio" : event.block === "scene_transition" ? "➡️ Ir para outra cena" : event.block; }
function summaryAfter(event: SceneEventDefinition, funnel: FunnelDefinition) { if (event.block === "notification") return `Ao tocar: ${actionLabel(event.onTap[0])}`; if (event.block === "scene_transition") return `Vai para: ${funnel.scenes.find((scene) => scene.id === event.targetSceneId)?.title || "escolha uma cena"}`; return `Depois: ${actionLabel(event.actions[0])}`; }
