/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevRouteImport } from './routes/dev'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as Dev14DaysRouteImport } from './routes/dev/14-days'
import { Route as DevAudioRouteImport } from './routes/dev/audio'
import { Route as DevChoiceRouteImport } from './routes/dev/choice'
import { Route as DevDebugRouteImport } from './routes/dev/debug'
import { Route as DevDoorSceneRouteImport } from './routes/dev/door-scene'
import { Route as DevFunnelRuntimeProofRouteImport } from './routes/dev/funnel-runtime-proof'
import { Route as DevFunnelStudioRouteImport } from './routes/dev/funnel-studio'
import { Route as DevHusbandTalkRouteImport } from './routes/dev/husband-talk'
import { Route as DevIncomingCallRouteImport } from './routes/dev/incoming-call'
import { Route as DevMilkSceneRouteImport } from './routes/dev/milk-scene'
import { Route as DevMotherCallRouteImport } from './routes/dev/mother-call'
import { Route as DevNotesRouteImport } from './routes/dev/notes'
import { Route as DevNotificationRouteImport } from './routes/dev/notification'
import { Route as DevPreloaderRouteImport } from './routes/dev/preloader'
import { Route as DevQuizRouteImport } from './routes/dev/quiz'
import { Route as DevR2UploadProofRouteImport } from './routes/dev/r2-upload-proof'
import { Route as DevRecordRouteImport } from './routes/dev/record'
import { Route as DevSceneRouteImport } from './routes/dev/scene'
import { Route as DevSecretWhatsappRouteImport } from './routes/dev/secret-whatsapp'
import { Route as DevTimelineRouteImport } from './routes/dev/timeline'
import { Route as DevTransitionsRouteImport } from './routes/dev/transitions'
import { Route as DevVideoStageRouteImport } from './routes/dev/video-stage'
import { Route as DevVoiceOnceRouteImport } from './routes/dev/voice-once'
import { Route as DevWhatsappRouteImport } from './routes/dev/whatsapp'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SignupSuccessRouteImport } from './routes/signup/success'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAdminRouteImport } from './routes/studio/admin'
import { Route as StudioBlueprintRouteImport } from './routes/studio/blueprint'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const Dev14DaysRoute = Dev14DaysRouteImport.update({
  id: '/14-days',
  path: '/14-days',
  getParentRoute: () => DevRoute,
} as any)
const DevAudioRoute = DevAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => DevRoute,
} as any)
const DevChoiceRoute = DevChoiceRouteImport.update({
  id: '/choice',
  path: '/choice',
  getParentRoute: () => DevRoute,
} as any)
const DevDebugRoute = DevDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => DevRoute,
} as any)
const DevDoorSceneRoute = DevDoorSceneRouteImport.update({
  id: '/door-scene',
  path: '/door-scene',
  getParentRoute: () => DevRoute,
} as any)
const DevFunnelRuntimeProofRoute = DevFunnelRuntimeProofRouteImport.update({
  id: '/funnel-runtime-proof',
  path: '/funnel-runtime-proof',
  getParentRoute: () => DevRoute,
} as any)
const DevFunnelStudioRoute = DevFunnelStudioRouteImport.update({
  id: '/funnel-studio',
  path: '/funnel-studio',
  getParentRoute: () => DevRoute,
} as any)
const DevHusbandTalkRoute = DevHusbandTalkRouteImport.update({
  id: '/husband-talk',
  path: '/husband-talk',
  getParentRoute: () => DevRoute,
} as any)
const DevIncomingCallRoute = DevIncomingCallRouteImport.update({
  id: '/incoming-call',
  path: '/incoming-call',
  getParentRoute: () => DevRoute,
} as any)
const DevMilkSceneRoute = DevMilkSceneRouteImport.update({
  id: '/milk-scene',
  path: '/milk-scene',
  getParentRoute: () => DevRoute,
} as any)
const DevMotherCallRoute = DevMotherCallRouteImport.update({
  id: '/mother-call',
  path: '/mother-call',
  getParentRoute: () => DevRoute,
} as any)
const DevNotesRoute = DevNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DevRoute,
} as any)
const DevNotificationRoute = DevNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => DevRoute,
} as any)
const DevPreloaderRoute = DevPreloaderRouteImport.update({
  id: '/preloader',
  path: '/preloader',
  getParentRoute: () => DevRoute,
} as any)
const DevQuizRoute = DevQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DevRoute,
} as any)
const DevR2UploadProofRoute = DevR2UploadProofRouteImport.update({
  id: '/r2-upload-proof',
  path: '/r2-upload-proof',
  getParentRoute: () => DevRoute,
} as any)
const DevRecordRoute = DevRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => DevRoute,
} as any)
const DevSceneRoute = DevSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => DevRoute,
} as any)
const DevSecretWhatsappRoute = DevSecretWhatsappRouteImport.update({
  id: '/secret-whatsapp',
  path: '/secret-whatsapp',
  getParentRoute: () => DevRoute,
} as any)
const DevTimelineRoute = DevTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DevRoute,
} as any)
const DevTransitionsRoute = DevTransitionsRouteImport.update({
  id: '/transitions',
  path: '/transitions',
  getParentRoute: () => DevRoute,
} as any)
const DevVideoStageRoute = DevVideoStageRouteImport.update({
  id: '/video-stage',
  path: '/video-stage',
  getParentRoute: () => DevRoute,
} as any)
const DevVoiceOnceRoute = DevVoiceOnceRouteImport.update({
  id: '/voice-once',
  path: '/voice-once',
  getParentRoute: () => DevRoute,
} as any)
const DevWhatsappRoute = DevWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DevRoute,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SignupSuccessRoute = SignupSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SignupRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAdminRoute = StudioAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBlueprintRoute = StudioBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteWithChildren
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/signup': typeof SignupRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/dev/14-days': typeof Dev14DaysRoute
  '/dev/audio': typeof DevAudioRoute
  '/dev/choice': typeof DevChoiceRoute
  '/dev/debug': typeof DevDebugRoute
  '/dev/door-scene': typeof DevDoorSceneRoute
  '/dev/funnel-runtime-proof': typeof DevFunnelRuntimeProofRoute
  '/dev/funnel-studio': typeof DevFunnelStudioRoute
  '/dev/husband-talk': typeof DevHusbandTalkRoute
  '/dev/incoming-call': typeof DevIncomingCallRoute
  '/dev/milk-scene': typeof DevMilkSceneRoute
  '/dev/mother-call': typeof DevMotherCallRoute
  '/dev/notes': typeof DevNotesRoute
  '/dev/notification': typeof DevNotificationRoute
  '/dev/preloader': typeof DevPreloaderRoute
  '/dev/quiz': typeof DevQuizRoute
  '/dev/r2-upload-proof': typeof DevR2UploadProofRoute
  '/dev/record': typeof DevRecordRoute
  '/dev/scene': typeof DevSceneRoute
  '/dev/secret-whatsapp': typeof DevSecretWhatsappRoute
  '/dev/timeline': typeof DevTimelineRoute
  '/dev/transitions': typeof DevTransitionsRoute
  '/dev/video-stage': typeof DevVideoStageRoute
  '/dev/voice-once': typeof DevVoiceOnceRoute
  '/dev/whatsapp': typeof DevWhatsappRoute
  '/signup/success': typeof SignupSuccessRoute
  '/studio/admin': typeof StudioAdminRoute
  '/studio/blueprint': typeof StudioBlueprintRoute
  '/dev/': typeof DevIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/dev/14-days': typeof Dev14DaysRoute
  '/dev/audio': typeof DevAudioRoute
  '/dev/choice': typeof DevChoiceRoute
  '/dev/debug': typeof DevDebugRoute
  '/dev/door-scene': typeof DevDoorSceneRoute
  '/dev/funnel-runtime-proof': typeof DevFunnelRuntimeProofRoute
  '/dev/funnel-studio': typeof DevFunnelStudioRoute
  '/dev/husband-talk': typeof DevHusbandTalkRoute
  '/dev/incoming-call': typeof DevIncomingCallRoute
  '/dev/milk-scene': typeof DevMilkSceneRoute
  '/dev/mother-call': typeof DevMotherCallRoute
  '/dev/notes': typeof DevNotesRoute
  '/dev/notification': typeof DevNotificationRoute
  '/dev/preloader': typeof DevPreloaderRoute
  '/dev/quiz': typeof DevQuizRoute
  '/dev/r2-upload-proof': typeof DevR2UploadProofRoute
  '/dev/record': typeof DevRecordRoute
  '/dev/scene': typeof DevSceneRoute
  '/dev/secret-whatsapp': typeof DevSecretWhatsappRoute
  '/dev/timeline': typeof DevTimelineRoute
  '/dev/transitions': typeof DevTransitionsRoute
  '/dev/video-stage': typeof DevVideoStageRoute
  '/dev/voice-once': typeof DevVoiceOnceRoute
  '/dev/whatsapp': typeof DevWhatsappRoute
  '/signup/success': typeof SignupSuccessRoute
  '/studio/admin': typeof StudioAdminRoute
  '/studio/blueprint': typeof StudioBlueprintRoute
  '/dev': typeof DevIndexRoute
  '/signup': typeof SignupIndexRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRouteWithChildren
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/signup': typeof SignupRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/dev/14-days': typeof Dev14DaysRoute
  '/dev/audio': typeof DevAudioRoute
  '/dev/choice': typeof DevChoiceRoute
  '/dev/debug': typeof DevDebugRoute
  '/dev/door-scene': typeof DevDoorSceneRoute
  '/dev/funnel-runtime-proof': typeof DevFunnelRuntimeProofRoute
  '/dev/funnel-studio': typeof DevFunnelStudioRoute
  '/dev/husband-talk': typeof DevHusbandTalkRoute
  '/dev/incoming-call': typeof DevIncomingCallRoute
  '/dev/milk-scene': typeof DevMilkSceneRoute
  '/dev/mother-call': typeof DevMotherCallRoute
  '/dev/notes': typeof DevNotesRoute
  '/dev/notification': typeof DevNotificationRoute
  '/dev/preloader': typeof DevPreloaderRoute
  '/dev/quiz': typeof DevQuizRoute
  '/dev/r2-upload-proof': typeof DevR2UploadProofRoute
  '/dev/record': typeof DevRecordRoute
  '/dev/scene': typeof DevSceneRoute
  '/dev/secret-whatsapp': typeof DevSecretWhatsappRoute
  '/dev/timeline': typeof DevTimelineRoute
  '/dev/transitions': typeof DevTransitionsRoute
  '/dev/video-stage': typeof DevVideoStageRoute
  '/dev/voice-once': typeof DevVoiceOnceRoute
  '/dev/whatsapp': typeof DevWhatsappRoute
  '/signup/success': typeof SignupSuccessRoute
  '/studio/admin': typeof StudioAdminRoute
  '/studio/blueprint': typeof StudioBlueprintRoute
  '/dev/': typeof DevIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/intro'
    | '/login'
    | '/notas'
    | '/signup'
    | '/studio'
    | '/dev/14-days'
    | '/dev/audio'
    | '/dev/choice'
    | '/dev/debug'
    | '/dev/door-scene'
    | '/dev/funnel-runtime-proof'
    | '/dev/funnel-studio'
    | '/dev/husband-talk'
    | '/dev/incoming-call'
    | '/dev/milk-scene'
    | '/dev/mother-call'
    | '/dev/notes'
    | '/dev/notification'
    | '/dev/preloader'
    | '/dev/quiz'
    | '/dev/r2-upload-proof'
    | '/dev/record'
    | '/dev/scene'
    | '/dev/secret-whatsapp'
    | '/dev/timeline'
    | '/dev/transitions'
    | '/dev/video-stage'
    | '/dev/voice-once'
    | '/dev/whatsapp'
    | '/signup/success'
    | '/studio/admin'
    | '/studio/blueprint'
    | '/dev/'
    | '/signup/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intro'
    | '/login'
    | '/notas'
    | '/dev/14-days'
    | '/dev/audio'
    | '/dev/choice'
    | '/dev/debug'
    | '/dev/door-scene'
    | '/dev/funnel-runtime-proof'
    | '/dev/funnel-studio'
    | '/dev/husband-talk'
    | '/dev/incoming-call'
    | '/dev/milk-scene'
    | '/dev/mother-call'
    | '/dev/notes'
    | '/dev/notification'
    | '/dev/preloader'
    | '/dev/quiz'
    | '/dev/r2-upload-proof'
    | '/dev/record'
    | '/dev/scene'
    | '/dev/secret-whatsapp'
    | '/dev/timeline'
    | '/dev/transitions'
    | '/dev/video-stage'
    | '/dev/voice-once'
    | '/dev/whatsapp'
    | '/signup/success'
    | '/studio/admin'
    | '/studio/blueprint'
    | '/dev'
    | '/signup'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/intro'
    | '/login'
    | '/notas'
    | '/signup'
    | '/studio'
    | '/dev/14-days'
    | '/dev/audio'
    | '/dev/choice'
    | '/dev/debug'
    | '/dev/door-scene'
    | '/dev/funnel-runtime-proof'
    | '/dev/funnel-studio'
    | '/dev/husband-talk'
    | '/dev/incoming-call'
    | '/dev/milk-scene'
    | '/dev/mother-call'
    | '/dev/notes'
    | '/dev/notification'
    | '/dev/preloader'
    | '/dev/quiz'
    | '/dev/r2-upload-proof'
    | '/dev/record'
    | '/dev/scene'
    | '/dev/secret-whatsapp'
    | '/dev/timeline'
    | '/dev/transitions'
    | '/dev/video-stage'
    | '/dev/voice-once'
    | '/dev/whatsapp'
    | '/signup/success'
    | '/studio/admin'
    | '/studio/blueprint'
    | '/dev/'
    | '/signup/'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRoute: typeof DevRouteWithChildren
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  NotasRoute: typeof NotasRoute
  SignupRoute: typeof SignupRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/14-days': {
      id: '/dev/14-days'
      path: '/14-days'
      fullPath: '/dev/14-days'
      preLoaderRoute: typeof Dev14DaysRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/audio': {
      id: '/dev/audio'
      path: '/audio'
      fullPath: '/dev/audio'
      preLoaderRoute: typeof DevAudioRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/choice': {
      id: '/dev/choice'
      path: '/choice'
      fullPath: '/dev/choice'
      preLoaderRoute: typeof DevChoiceRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/debug': {
      id: '/dev/debug'
      path: '/debug'
      fullPath: '/dev/debug'
      preLoaderRoute: typeof DevDebugRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/door-scene': {
      id: '/dev/door-scene'
      path: '/door-scene'
      fullPath: '/dev/door-scene'
      preLoaderRoute: typeof DevDoorSceneRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/funnel-runtime-proof': {
      id: '/dev/funnel-runtime-proof'
      path: '/funnel-runtime-proof'
      fullPath: '/dev/funnel-runtime-proof'
      preLoaderRoute: typeof DevFunnelRuntimeProofRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/funnel-studio': {
      id: '/dev/funnel-studio'
      path: '/funnel-studio'
      fullPath: '/dev/funnel-studio'
      preLoaderRoute: typeof DevFunnelStudioRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/husband-talk': {
      id: '/dev/husband-talk'
      path: '/husband-talk'
      fullPath: '/dev/husband-talk'
      preLoaderRoute: typeof DevHusbandTalkRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/incoming-call': {
      id: '/dev/incoming-call'
      path: '/incoming-call'
      fullPath: '/dev/incoming-call'
      preLoaderRoute: typeof DevIncomingCallRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/milk-scene': {
      id: '/dev/milk-scene'
      path: '/milk-scene'
      fullPath: '/dev/milk-scene'
      preLoaderRoute: typeof DevMilkSceneRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/mother-call': {
      id: '/dev/mother-call'
      path: '/mother-call'
      fullPath: '/dev/mother-call'
      preLoaderRoute: typeof DevMotherCallRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/notes': {
      id: '/dev/notes'
      path: '/notes'
      fullPath: '/dev/notes'
      preLoaderRoute: typeof DevNotesRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/notification': {
      id: '/dev/notification'
      path: '/notification'
      fullPath: '/dev/notification'
      preLoaderRoute: typeof DevNotificationRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/preloader': {
      id: '/dev/preloader'
      path: '/preloader'
      fullPath: '/dev/preloader'
      preLoaderRoute: typeof DevPreloaderRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/quiz': {
      id: '/dev/quiz'
      path: '/quiz'
      fullPath: '/dev/quiz'
      preLoaderRoute: typeof DevQuizRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/r2-upload-proof': {
      id: '/dev/r2-upload-proof'
      path: '/r2-upload-proof'
      fullPath: '/dev/r2-upload-proof'
      preLoaderRoute: typeof DevR2UploadProofRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/record': {
      id: '/dev/record'
      path: '/record'
      fullPath: '/dev/record'
      preLoaderRoute: typeof DevRecordRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/scene': {
      id: '/dev/scene'
      path: '/scene'
      fullPath: '/dev/scene'
      preLoaderRoute: typeof DevSceneRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/secret-whatsapp': {
      id: '/dev/secret-whatsapp'
      path: '/secret-whatsapp'
      fullPath: '/dev/secret-whatsapp'
      preLoaderRoute: typeof DevSecretWhatsappRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/timeline': {
      id: '/dev/timeline'
      path: '/timeline'
      fullPath: '/dev/timeline'
      preLoaderRoute: typeof DevTimelineRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/transitions': {
      id: '/dev/transitions'
      path: '/transitions'
      fullPath: '/dev/transitions'
      preLoaderRoute: typeof DevTransitionsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/video-stage': {
      id: '/dev/video-stage'
      path: '/video-stage'
      fullPath: '/dev/video-stage'
      preLoaderRoute: typeof DevVideoStageRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/voice-once': {
      id: '/dev/voice-once'
      path: '/voice-once'
      fullPath: '/dev/voice-once'
      preLoaderRoute: typeof DevVoiceOnceRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/whatsapp': {
      id: '/dev/whatsapp'
      path: '/whatsapp'
      fullPath: '/dev/whatsapp'
      preLoaderRoute: typeof DevWhatsappRouteImport
      parentRoute: typeof DevRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/success': {
      id: '/signup/success'
      path: '/success'
      fullPath: '/signup/success'
      preLoaderRoute: typeof SignupSuccessRouteImport
      parentRoute: typeof SignupRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/admin': {
      id: '/studio/admin'
      path: '/admin'
      fullPath: '/studio/admin'
      preLoaderRoute: typeof StudioAdminRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/blueprint': {
      id: '/studio/blueprint'
      path: '/blueprint'
      fullPath: '/studio/blueprint'
      preLoaderRoute: typeof StudioBlueprintRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface DevRouteChildren {
  Dev14DaysRoute: typeof Dev14DaysRoute
  DevAudioRoute: typeof DevAudioRoute
  DevChoiceRoute: typeof DevChoiceRoute
  DevDebugRoute: typeof DevDebugRoute
  DevDoorSceneRoute: typeof DevDoorSceneRoute
  DevFunnelRuntimeProofRoute: typeof DevFunnelRuntimeProofRoute
  DevFunnelStudioRoute: typeof DevFunnelStudioRoute
  DevHusbandTalkRoute: typeof DevHusbandTalkRoute
  DevIncomingCallRoute: typeof DevIncomingCallRoute
  DevMilkSceneRoute: typeof DevMilkSceneRoute
  DevMotherCallRoute: typeof DevMotherCallRoute
  DevNotesRoute: typeof DevNotesRoute
  DevNotificationRoute: typeof DevNotificationRoute
  DevPreloaderRoute: typeof DevPreloaderRoute
  DevQuizRoute: typeof DevQuizRoute
  DevR2UploadProofRoute: typeof DevR2UploadProofRoute
  DevRecordRoute: typeof DevRecordRoute
  DevSceneRoute: typeof DevSceneRoute
  DevSecretWhatsappRoute: typeof DevSecretWhatsappRoute
  DevTimelineRoute: typeof DevTimelineRoute
  DevTransitionsRoute: typeof DevTransitionsRoute
  DevVideoStageRoute: typeof DevVideoStageRoute
  DevVoiceOnceRoute: typeof DevVoiceOnceRoute
  DevWhatsappRoute: typeof DevWhatsappRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  Dev14DaysRoute: Dev14DaysRoute,
  DevAudioRoute: DevAudioRoute,
  DevChoiceRoute: DevChoiceRoute,
  DevDebugRoute: DevDebugRoute,
  DevDoorSceneRoute: DevDoorSceneRoute,
  DevFunnelRuntimeProofRoute: DevFunnelRuntimeProofRoute,
  DevFunnelStudioRoute: DevFunnelStudioRoute,
  DevHusbandTalkRoute: DevHusbandTalkRoute,
  DevIncomingCallRoute: DevIncomingCallRoute,
  DevMilkSceneRoute: DevMilkSceneRoute,
  DevMotherCallRoute: DevMotherCallRoute,
  DevNotesRoute: DevNotesRoute,
  DevNotificationRoute: DevNotificationRoute,
  DevPreloaderRoute: DevPreloaderRoute,
  DevQuizRoute: DevQuizRoute,
  DevR2UploadProofRoute: DevR2UploadProofRoute,
  DevRecordRoute: DevRecordRoute,
  DevSceneRoute: DevSceneRoute,
  DevSecretWhatsappRoute: DevSecretWhatsappRoute,
  DevTimelineRoute: DevTimelineRoute,
  DevTransitionsRoute: DevTransitionsRoute,
  DevVideoStageRoute: DevVideoStageRoute,
  DevVoiceOnceRoute: DevVoiceOnceRoute,
  DevWhatsappRoute: DevWhatsappRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface SignupRouteChildren {
  SignupSuccessRoute: typeof SignupSuccessRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSuccessRoute: SignupSuccessRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface StudioRouteChildren {
  StudioAdminRoute: typeof StudioAdminRoute
  StudioBlueprintRoute: typeof StudioBlueprintRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAdminRoute: StudioAdminRoute,
  StudioBlueprintRoute: StudioBlueprintRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRouteWithChildren,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  NotasRoute: NotasRoute,
  SignupRoute: SignupRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
