import type { ActionDefinition, FunnelDefinition, SceneEventDefinition } from '../schema/v1';
import { funnelBlockRegistry } from '../registry/blockRegistry';

export type EventStatus = 'armed' | 'fired' | 'active' | 'completed' | 'skipped';
export type MediaError = { kind: 'media_error'; assetId?: string; eventId: string; sceneId: string; errorType: string };
export type RuntimeSnapshot = { funnelId: string; sceneId: string; runId: number; currentTime: number; duration: number | null; mediaState: 'idle'|'playing'|'paused'|'ended'|'stopped'; activeBlockingEventId: string | null; activeInteraction: { id: string; sourceEventId: string } | null; events: Record<string, EventStatus>; executedActions: string[]; navigationHistory: string[]; mediaErrors: MediaError[] };

export class FunnelRuntime {
  private sceneId: string; private runId = 1; private currentTime = 0; private duration: number | null = null;
  private mediaState: RuntimeSnapshot['mediaState'] = 'idle'; private eventStates = new Map<string, EventStatus>();
  private activeInteraction: RuntimeSnapshot['activeInteraction'] = null; private activeBlockingEventId: string | null = null;
  private executedActions: string[] = []; private navigationHistory: string[]; private mediaErrors: MediaError[] = []; private listeners = new Set<(s: RuntimeSnapshot) => void>();
  constructor(private readonly funnel: FunnelDefinition) { this.sceneId = funnel.entrySceneId; this.navigationHistory = [this.sceneId]; this.armScene(); }
  subscribe(listener: (snapshot: RuntimeSnapshot) => void) { this.listeners.add(listener); listener(this.snapshot()); return () => { this.listeners.delete(listener); }; }
  private emit() { const s = this.snapshot(); this.listeners.forEach(listener => listener(s)); }
  private scene() { const scene = this.funnel.scenes.find(item => item.id === this.sceneId); if (!scene) throw new Error(`Unknown scene: ${this.sceneId}`); return scene; }
  private armScene() { this.eventStates.clear(); this.scene().events.forEach(event => this.eventStates.set(event.id, 'armed')); this.activeInteraction = null; this.activeBlockingEventId = null; this.currentTime = 0; this.duration = this.scene().duration ?? null; this.mediaState = 'idle'; }
  start() { const run = this.runId; this.mediaState = 'playing'; this.fireMatching('SCENE_START', run); this.emit(); return run; }
  reset() { this.runId++; this.armScene(); this.emit(); return this.runId; }
  enterScene(sceneId: string) { if (!this.funnel.scenes.some(scene => scene.id === sceneId)) return false; this.runId++; this.sceneId = sceneId; this.navigationHistory.push(sceneId); this.armScene(); this.start(); return true; }
  setDuration(duration: number, runId = this.runId) { if (runId !== this.runId || !Number.isFinite(duration) || duration <= 0) return; this.duration = duration; this.emit(); }
  updateTime(currentTime: number, runId = this.runId) { if (runId !== this.runId || this.activeBlockingEventId) return; const from = this.currentTime; this.currentTime = Math.max(0, currentTime); if (this.currentTime >= from) this.scene().events.filter(e => e.trigger.kind === 'TIME' && from < e.trigger.seconds && this.currentTime >= e.trigger.seconds).forEach(e => this.fire(e, runId)); if (this.duration !== null) this.scene().events.filter(e => e.trigger.kind === 'BEFORE_END' && from < this.duration! - e.trigger.seconds && this.currentTime >= this.duration! - e.trigger.seconds).forEach(e => this.fire(e, runId)); this.emit(); }
  seek(currentTime: number, runId = this.runId) { if (runId !== this.runId) return; const previous = this.currentTime; const next = Math.max(0, currentTime); if (next >= previous) { this.currentTime = previous; this.updateTime(next, runId); } else { this.currentTime = next; for (const event of this.scene().events) { const triggerTime = event.trigger.kind === 'TIME' ? event.trigger.seconds : event.trigger.kind === 'BEFORE_END' && this.duration !== null ? this.duration - event.trigger.seconds : null; if (triggerTime !== null && triggerTime > this.currentTime && this.eventStates.get(event.id) !== 'completed') this.eventStates.set(event.id, 'armed'); } this.emit(); } }
  mediaEnded(runId = this.runId) { if (runId !== this.runId) return; this.mediaState = 'ended'; this.fireMatching('VIDEO_END', runId); this.emit(); }
  fireManual(eventId: string, runId = this.runId) { if (runId !== this.runId) return false; const event = this.scene().events.find(e => e.id === eventId && e.trigger.kind === 'MANUAL'); if (!event) return false; return this.fire(event, runId); }
  private fireMatching(kind: 'SCENE_START'|'VIDEO_END', runId: number) { this.scene().events.filter(event => event.trigger.kind === kind).forEach(event => this.fire(event, runId)); }
  private fire(event: SceneEventDefinition, runId: number) { if (runId !== this.runId || this.eventStates.get(event.id) !== 'armed') return false; this.eventStates.set(event.id, funnelBlockRegistry.isBlocking(event) ? 'active' : 'fired'); if (funnelBlockRegistry.isBlocking(event)) { this.activeBlockingEventId = event.id; this.activeInteraction = { id: event.id, sourceEventId: event.id }; this.mediaState = 'paused'; } else { this.eventStates.set(event.id, 'completed'); this.execute(event.actions, event.id, runId); } return true; }
  completeInteraction(interactionId: string, runId = this.runId) { if (runId !== this.runId || !this.activeInteraction || this.activeInteraction.id !== interactionId) return false; const sourceEventId = this.activeInteraction.sourceEventId; if (this.eventStates.get(sourceEventId) !== 'active') return false; this.eventStates.set(sourceEventId, 'completed'); this.activeInteraction = null; this.activeBlockingEventId = null; const event = this.scene().events.find(item => item.id === sourceEventId); if (event) { this.execute(event.actions, sourceEventId, runId); this.scene().events.filter(item => item.trigger.kind === 'INTERACTION_COMPLETE' && item.trigger.interactionId === interactionId).forEach(item => this.fire(item, runId)); } this.emit(); return true; }
  execute(actions: readonly ActionDefinition[], sourceEventId: string, runId = this.runId) { if (runId !== this.runId) return; for (const action of actions) { const key = `${runId}:${sourceEventId}:${action.type}:${'sceneId' in action ? action.sceneId : 'eventId' in action ? action.eventId : ''}`; if (this.executedActions.includes(key)) continue; this.executedActions.push(key); if (action.type === 'RESUME_VIDEO') this.mediaState = 'playing'; if (action.type === 'PAUSE_VIDEO') this.mediaState = 'paused'; if (action.type === 'STOP') this.mediaState = 'stopped'; if (action.type === 'NEXT_SCENE') { const target = this.scene().nextSceneId; if (target) this.enterScene(target); } if (action.type === 'GO_TO_SCENE') this.enterScene(action.sceneId); if (action.type === 'OPEN_EVENT') { const event = this.scene().events.find(item => item.id === action.eventId); if (event) this.fire(event, this.runId); } if (action.type === 'COMPLETE_SCENE') this.mediaState = 'ended'; } this.emit(); }
  reportMediaError(eventId: string, errorType: string, assetId?: string, runId = this.runId) { if (runId !== this.runId) return; this.mediaErrors.push({ kind: 'media_error', eventId, sceneId: this.sceneId, errorType, ...(assetId ? { assetId } : {}) }); this.emit(); }
  snapshot(): RuntimeSnapshot { return { funnelId: this.funnel.id, sceneId: this.sceneId, runId: this.runId, currentTime: this.currentTime, duration: this.duration, mediaState: this.mediaState, activeBlockingEventId: this.activeBlockingEventId, activeInteraction: this.activeInteraction, events: Object.fromEntries(this.eventStates), executedActions: [...this.executedActions], navigationHistory: [...this.navigationHistory], mediaErrors: [...this.mediaErrors] }; }
}
